import random

def out(query_list):
    random_index = random.randint(0, len(query_list) - 1)
    return query_list[random_index]

wel_output = ['How can I help you today?', 'Hey! What assistance do you need?', 'Greetings! How may I help you today?', 'Good day! What can I help with?', 'Hi! What’s your question today?', 'Hello! How can I assist you right now?', 'Hey there! What do you need help with?', 'Hi! How can I support you today?', 'Hello! What information are you looking for?', 'Hi! How may I assist you today?', 'Hello there! How can I help you out?', 'Hey! What can I assist you with today?', 'Hi! What’s on your mind today?', 'Hello! How can I help make your day easier?', 'Hi! What brings you here today?', 'Hey there! How can I assist you at this moment?', 'Greetings! What do you need assistance with?', 'Hello! How can I make things simpler for you?', 'Hi! How can I be of help today?', 'Hello there! What can I do for you today?', 'Hey! What help can I provide you with today?', 'Hi! How can I assist you right now?', 'Hello! What support can I offer you today?', 'Hi! How may I serve you today?', 'Hello there! What can I assist with today?', 'Hey! How can I be of service to you right now?', 'Hi! What do you need help with today?', 'Hello! How can I make things easier for you?', 'Hi! How can I assist you today?', 'Hello there! What can I help you with today?', 'Hey there! What can I do to assist you today?', 'Hi! How may I help you right now?', 'Hello! What support do you need today?', 'Hi! How can I be of service to you today?', 'Hello! What information are you seeking today?', 'Hi there! How can I help make your day better?', 'Hello! What assistance can I provide you with today?', 'Hey! What do you need help with right now?', 'Hi! How can I assist you at this moment?', 'Hello there! How can I help you today?', 'Hi! What’s your need today?', 'Hey there! How can I make things easier for you?', 'Hello! What help can I offer you right now?', 'Hi! How can I support you today?', 'Hello there! What can I do to assist you?', 'Hey! What’s on your mind today?', 'Hi! How can I be of assistance to you today?', 'Hello! What can I help you with right now?', 'Hi there! What can I do for you today?']

output = out(wel_output)
    